Sat 27 May 2017 16:08:35 API.py [line:546] INFO 200 statuses/filter text thread 0's token_index 394
Sat 27 May 2017 16:08:35 API.py [line:546] INFO 200 statuses/filter text thread 1's token_index 451
Sat 27 May 2017 16:08:35 API.py [line:546] INFO 200 statuses/filter text thread 2's token_index 225
Sat 27 May 2017 16:08:35 API.py [line:546] INFO 200 statuses/filter text thread 3's token_index 463
Sat 27 May 2017 16:08:35 API.py [line:546] INFO 200 statuses/filter text thread 4's token_index 488
Sat 27 May 2017 16:08:35 API.py [line:546] INFO 200 statuses/filter text thread 5's token_index 165
Sat 27 May 2017 16:08:35 API.py [line:546] INFO 200 statuses/filter text thread 7's token_index 304
Sat 27 May 2017 16:08:35 API.py [line:546] INFO 200 statuses/filter text thread 6's token_index 75
Sat 27 May 2017 16:08:35 API.py [line:546] INFO 200 statuses/filter text thread 8's token_index 517
Sat 27 May 2017 16:08:35 API.py [line:546] INFO 200 statuses/filter text thread 9's token_index 515
Sat 27 May 2017 16:08:35 API.py [line:546] INFO 200 statuses/filter text thread 10's token_index 207
Sat 27 May 2017 16:08:41 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:41 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:42 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:42 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:43 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:43 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:44 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:44 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:45 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:08:45 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:08:47 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:47 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:48 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:48 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:50 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> ('Connection aborted.', BadStatusLine("''",))
Sat 27 May 2017 16:08:50 API.py [line:207] WARNING ('Connection aborted.', BadStatusLine("''",))
Sat 27 May 2017 16:08:51 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> ('Connection aborted.', BadStatusLine("''",))
Sat 27 May 2017 16:08:51 API.py [line:207] WARNING ('Connection aborted.', BadStatusLine("''",))
Sat 27 May 2017 16:08:53 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:53 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:55 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:55 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:56 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> ('Connection aborted.', BadStatusLine("''",))
Sat 27 May 2017 16:08:56 API.py [line:207] WARNING ('Connection aborted.', BadStatusLine("''",))
Sat 27 May 2017 16:08:56 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> ('Connection aborted.', BadStatusLine("''",))
Sat 27 May 2017 16:08:56 API.py [line:207] WARNING ('Connection aborted.', BadStatusLine("''",))
Sat 27 May 2017 16:08:56 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> ('Connection aborted.', BadStatusLine("''",))
Sat 27 May 2017 16:08:56 API.py [line:207] WARNING ('Connection aborted.', BadStatusLine("''",))
Sat 27 May 2017 16:08:56 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:08:56 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:00 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:00 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:03 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:03 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:04 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:04 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:05 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:05 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:06 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:06 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:08 TwitterError.py [line:21] WARNING <class 'requests.exceptions.SSLError'> ('_ssl.c:645: The handshake operation timed out',)
Sat 27 May 2017 16:09:08 API.py [line:207] WARNING ('_ssl.c:645: The handshake operation timed out',)
Sat 27 May 2017 16:09:08 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:08 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:09 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:09 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:13 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:13 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:14 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:14 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:19 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:19 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:09:24 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:09:24 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:09:28 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'2440883438', u'user_id': 2440883438L, u'id': 868356908268343296L, u'id_str': u'868356908268343296'}, u'timestamp_ms': u'1495872548193'}}
Sat 27 May 2017 16:09:29 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:09:29 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:09:35 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'964546038', u'user_id': 964546038, u'id': 866404114493837313L, u'id_str': u'866404114493837313'}, u'timestamp_ms': u'1495872562897'}}
Sat 27 May 2017 16:09:35 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'964546038', u'user_id': 964546038, u'id': 866403902165594112L, u'id_str': u'866403902165594112'}, u'timestamp_ms': u'1495872563086'}}
Sat 27 May 2017 16:09:35 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'2810009016', u'user_id': 2810009016L, u'id': 866403573206319107L, u'id_str': u'866403573206319107'}, u'timestamp_ms': u'1495872563087'}}
Sat 27 May 2017 16:09:37 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'2809611224', u'user_id': 2809611224L, u'id': 868212243590152192L, u'id_str': u'868212243590152192'}, u'timestamp_ms': u'1495872541638'}}
Sat 27 May 2017 16:09:40 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'330895534', u'user_id': 330895534, u'id': 867867430919569412L, u'id_str': u'867867430919569412'}, u'timestamp_ms': u'1495872556240'}}
Sat 27 May 2017 16:09:44 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'3083244475', u'user_id': 3083244475L, u'id': 868124970026717186L, u'id_str': u'868124970026717186'}, u'timestamp_ms': u'1495872580777'}}
Sat 27 May 2017 16:09:44 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'569581021', u'user_id': 569581021, u'id': 868375930892308483L, u'id_str': u'868375930892308483'}, u'timestamp_ms': u'1495872565465'}}
Sat 27 May 2017 16:10:02 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'330895534', u'user_id': 330895534, u'id': 867763832143433729L, u'id_str': u'867763832143433729'}, u'timestamp_ms': u'1495872570619'}}
Sat 27 May 2017 16:10:03 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'47316108', u'user_id': 47316108, u'id': 868254888232460288L, u'id_str': u'868254888232460288'}, u'timestamp_ms': u'1495872594979'}}
Sat 27 May 2017 16:10:04 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'3083244475', u'user_id': 3083244475L, u'id': 868124834659741696L, u'id_str': u'868124834659741696'}, u'timestamp_ms': u'1495872589483'}}
Sat 27 May 2017 16:10:13 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'569581021', u'user_id': 569581021, u'id': 868375964538912768L, u'id_str': u'868375964538912768'}, u'timestamp_ms': u'1495872573369'}}
Sat 27 May 2017 16:10:27 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'569581021', u'user_id': 569581021, u'id': 868375991952883712L, u'id_str': u'868375991952883712'}, u'timestamp_ms': u'1495872579424'}}
Sat 27 May 2017 16:10:35 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'3083244475', u'user_id': 3083244475L, u'id': 868068502250430464L, u'id_str': u'868068502250430464'}, u'timestamp_ms': u'1495872613667'}}
Sat 27 May 2017 16:10:38 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'126625621', u'user_id': 126625621, u'id': 868094283252985857L, u'id_str': u'868094283252985857'}, u'timestamp_ms': u'1495872596894'}}
Sat 27 May 2017 16:10:39 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'330895534', u'user_id': 330895534, u'id': 867282851993178112L, u'id_str': u'867282851993178112'}, u'timestamp_ms': u'1495872597991'}}
Sat 27 May 2017 16:10:53 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'569581021', u'user_id': 569581021, u'id': 868376046902444032L, u'id_str': u'868376046902444032'}, u'timestamp_ms': u'1495872587622'}}
Sat 27 May 2017 16:10:54 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'3083244475', u'user_id': 3083244475L, u'id': 868062997318516736L, u'id_str': u'868062997318516736'}, u'timestamp_ms': u'1495872633495'}}
Sat 27 May 2017 16:10:55 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'18375327', u'user_id': 18375327, u'id': 833436072432513025L, u'id_str': u'833436072432513025'}, u'timestamp_ms': u'1495872587861'}}
Sat 27 May 2017 16:10:58 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'330895534', u'user_id': 330895534, u'id': 867267569786343425L, u'id_str': u'867267569786343425'}, u'timestamp_ms': u'1495872614558'}}
Sat 27 May 2017 16:11:04 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'3083244475', u'user_id': 3083244475L, u'id': 867221538969464836L, u'id_str': u'867221538969464836'}, u'timestamp_ms': u'1495872649178'}}
Sat 27 May 2017 16:11:20 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'330895534', u'user_id': 330895534, u'id': 867137121815064576L, u'id_str': u'867137121815064576'}, u'timestamp_ms': u'1495872620784'}}
Sat 27 May 2017 16:11:26 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'110437588', u'user_id': 110437588, u'id': 868215393017634816L, u'id_str': u'868215393017634816'}, u'timestamp_ms': u'1495872623144'}}
Sat 27 May 2017 16:11:28 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'330895534', u'user_id': 330895534, u'id': 867115286100660224L, u'id_str': u'867115286100660224'}, u'timestamp_ms': u'1495872629534'}}
Sat 27 May 2017 16:11:31 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'569581021', u'user_id': 569581021, u'id': 868376075381821441L, u'id_str': u'868376075381821441'}, u'timestamp_ms': u'1495872594528'}}
Sat 27 May 2017 16:11:34 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'3083244475', u'user_id': 3083244475L, u'id': 866651988465000449L, u'id_str': u'866651988465000449'}, u'timestamp_ms': u'1495872671756'}}
Sat 27 May 2017 16:11:36 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'18716851', u'user_id': 18716851, u'id': 868378307678568448L, u'id_str': u'868378307678568448'}, u'timestamp_ms': u'1495872668820'}}
Sat 27 May 2017 16:11:42 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'511740616', u'user_id': 511740616, u'id': 597815583158226944L, u'id_str': u'597815583158226944'}, u'timestamp_ms': u'1495872690974'}}
Sat 27 May 2017 16:11:47 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'164690458', u'user_id': 164690458, u'id': 868378035124408320L, u'id_str': u'868378035124408320'}, u'timestamp_ms': u'1495872682547'}}
Sat 27 May 2017 16:11:52 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'151876540', u'user_id': 151876540, u'id': 868163391298383872L, u'id_str': u'868163391298383872'}, u'timestamp_ms': u'1495872639035'}}
Sat 27 May 2017 16:11:54 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'38205414', u'user_id': 38205414, u'id': 868378360761790464L, u'id_str': u'868378360761790464'}, u'timestamp_ms': u'1495872693121'}}
Sat 27 May 2017 16:12:11 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'4705502727', u'user_id': 4705502727L, u'id': 868322801601662978L, u'id_str': u'868322801601662978'}, u'timestamp_ms': u'1495872728537'}}
Sat 27 May 2017 16:12:15 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'410345806', u'user_id': 410345806, u'id': 868378768561364992L, u'id_str': u'868378768561364992'}, u'timestamp_ms': u'1495872664713'}}
Sat 27 May 2017 16:12:20 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'21352483', u'user_id': 21352483, u'id': 603583296287670272L, u'id_str': u'603583296287670272'}, u'timestamp_ms': u'1495872697464'}}
Sat 27 May 2017 16:12:20 TwitterError.py [line:21] WARNING <class 'requests.packages.urllib3.exceptions.ReadTimeoutError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Read timed out.
Sat 27 May 2017 16:12:40 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'3083244475', u'user_id': 3083244475L, u'id': 865970972515606528L, u'id_str': u'865970972515606528'}, u'timestamp_ms': u'1495872729196'}}
Sat 27 May 2017 16:12:45 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'1252857842', u'user_id': 1252857842, u'id': 868016600783441920L, u'id_str': u'868016600783441920'}, u'timestamp_ms': u'1495872687056'}}
Sat 27 May 2017 16:12:51 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'3083244475', u'user_id': 3083244475L, u'id': 865553465652592640L, u'id_str': u'865553465652592640'}, u'timestamp_ms': u'1495872737723'}}
Sat 27 May 2017 16:12:55 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'3083244475', u'user_id': 3083244475L, u'id': 865553211515469827L, u'id_str': u'865553211515469827'}, u'timestamp_ms': u'1495872743290'}}
Sat 27 May 2017 16:13:00 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'2192072359', u'user_id': 2192072359L, u'id': 868377912638136320L, u'id_str': u'868377912638136320'}, u'timestamp_ms': u'1495872728465'}}
Sat 27 May 2017 16:13:04 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'193030139', u'user_id': 193030139, u'id': 597810413930213377L, u'id_str': u'597810413930213377'}, u'timestamp_ms': u'1495872691193'}}
Sat 27 May 2017 16:13:07 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'3083244475', u'user_id': 3083244475L, u'id': 865523468418207744L, u'id_str': u'865523468418207744'}, u'timestamp_ms': u'1495872761557'}}
Sat 27 May 2017 16:13:09 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'868637460', u'user_id': 868637460, u'id': 581843039993237505L, u'id_str': u'581843039993237505'}, u'timestamp_ms': u'1495872785044'}}
Sat 27 May 2017 16:13:12 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'38205414', u'user_id': 38205414, u'id': 868368324106825732L, u'id_str': u'868368324106825732'}, u'timestamp_ms': u'1495872764157'}}
Sat 27 May 2017 16:13:13 TwitterError.py [line:21] WARNING <class 'requests.packages.urllib3.exceptions.ReadTimeoutError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Read timed out.
Sat 27 May 2017 16:14:02 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'532285060', u'user_id': 532285060, u'id': 854173262636621825L, u'id_str': u'854173262636621825'}, u'timestamp_ms': u'1495872810766'}}
